In [101]:
from IPython.display import Image
import numpy as np

In [1]:
import torch
torch.__version__

'1.12.1+cu102'

#### Creating Tensors

In [7]:
#  scalar tensor
scalar_tensor =torch.tensor(7)
print(scalar_tensor)

print(scalar_tensor.__class__)

# shape of a tensor
print(scalar_tensor.ndim)

# shape of a tensor
print(scalar_tensor.shape)

# turn the pytorch tenmsor to python number
print(scalar_tensor.item())

tensor(7)
<class 'torch.Tensor'>
0
torch.Size([])


In [11]:
#  vector
vector_tensor = torch.tensor([1,2,3,4,5])
print(vector_tensor)

# shape of a tensor vector
print(vector_tensor.ndim)

# shape of a tensor vector
print(vector_tensor.shape)

#  turn the pytorch tenmsor to python list
print(vector_tensor.tolist())

tensor([1, 2, 3, 4, 5])
1
torch.Size([5])
[1, 2, 3, 4, 5]


In [12]:
#  matrix
matrix_tensor = torch.tensor([[1,2,3,4,5],[6,7,8,9,10]])
print(matrix_tensor)

# shape of a tensor matrix
print(matrix_tensor.ndim)

# shape of a tensor matrix
print(matrix_tensor.shape)

#  turn the pytorch tenmsor to python list
print(matrix_tensor.tolist())

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])
2
torch.Size([2, 5])
[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]


In [13]:
#  create 3d tensor in pytorch
tensor_3d = torch.tensor([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(tensor_3d)

# shape of a tensor 3d
print(tensor_3d.ndim)

# shape of a tensor 3d
print(tensor_3d.shape)

#  turn the pytorch tenmsor to python list
print(tensor_3d.tolist())

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])
3
torch.Size([2, 2, 3])
[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]


In [16]:
# show the image from the web

image_url = "https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-pytorch-different-tensor-dimensions.png"
Image(url= image_url, width=800, height=400)

#### Creating Random Tensors

In [27]:
#  create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
print(f"random_tensor vlaue is \n {random_tensor}, \n its data type is \n {random_tensor.dtype}")

random_tensor vlaue is 
 tensor([[0.9402, 0.1363, 0.7646, 0.8853],
        [0.7855, 0.8835, 0.4324, 0.3900],
        [0.6175, 0.6068, 0.6155, 0.5684]]), 
 its data type is 
 torch.float32


In [28]:
# Create a random tensor of size (224, 224, 3)
random_tensor = torch.rand(224, 224, 3)
print(f"random_tensor vlaue dimesnion is is \n {random_tensor.ndim}, \n its shape is \n {random_tensor.shape}")

random_tensor vlaue dimesnion is is 
 3, 
 its shape is 
 torch.Size([224, 224, 3])


#### Creating Zeros and Ones Tenors 

In [30]:
# Create a tensor of all zeros
tensor_of_zeros = torch.zeros(3,4)
print(tensor_of_zeros, tensor_of_zeros.dtype)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]) torch.float32


In [31]:
# Create a tensor of all ones
tensor_of_ones = torch.ones(3,4)
print(tensor_of_ones, tensor_of_ones.dtype)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) torch.float32


#### Creating a Range and Tensors Like

In [33]:
#  create tesnors in a specific range
tensor_in_range = torch.arange(start=0, end=10, step=2)
print(tensor_in_range)

tensor([0, 2, 4, 6, 8])


In [34]:
# zero tensors with the same shape as tensor_in_range
zero_tensor = torch.zeros_like(tensor_in_range)
print(zero_tensor)

tensor([0, 0, 0, 0, 0])


#### Tensor datatypes 

In [37]:
#  Create a tensor with the dfeault datatype in pytroch
tensor_default = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]],
                              dtype=None,
                              device=None,
                              requires_grad=False)
print(tensor_default.shape, tensor_default.dtype, tensor_default.device, tensor_default.requires_grad)


torch.Size([2, 3]) torch.float32 cpu False


In [38]:
#  Create a tensor with the float16 datatype in pytroch
tensor_float16 = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]],
                                dtype=torch.float16,
                                device=None,
                                requires_grad=False)

print(tensor_float16.shape, tensor_float16.dtype, tensor_float16.device, tensor_float16.requires_grad)

torch.Size([2, 3]) torch.float16 cpu False


#### Getting Information from Tensors

In [41]:
#  Create a tensor in pytorch
temp_tensor = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])

# Get the ifnormation of the tensor
print(f"tesnor shape is {temp_tensor.shape}")
print(f"tesnor data type is {temp_tensor.dtype}")
print(f"tesnor is stored on {temp_tensor.device}")

tesnor shape is torch.Size([2, 3])
tesnor data type is torch.float32
tesnor is stored on cpu


#### Manipulating Tensors (Tensor Pperations)

##### Basic Operations

In [55]:
# Create a tensor of values
temp_tensor = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])

#  Add a number to it
print(temp_tensor+10.0)

# # Multiply it by 10.25
print(temp_tensor * 10.25)

# Tensors don't change unless reassigned
print(temp_tensor)

# Subtract and reassign
temp_tensor = temp_tensor - 10.0
print(temp_tensor)

#  Add and reassign
temp_tensor = temp_tensor + 10.0
print(temp_tensor)

# Element-wise multiplication
print(temp_tensor * temp_tensor)

# Matrix multiplication with @ operator
print(temp_tensor @ temp_tensor.T)

tensor([[11., 12., 13.],
        [14., 15., 16.]])
tensor([[10.2500, 20.5000, 30.7500],
        [41.0000, 51.2500, 61.5000]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[-9., -8., -7.],
        [-6., -5., -4.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])
tensor([[14., 32.],
        [32., 77.]])


In [54]:
temp_tensor = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])

# Add a number to it with torch function
print(torch.add(temp_tensor, 10.0))

#  Multiply it by 10.25 with torch function
print(torch.mul(temp_tensor, 10.25))

# Subtract and reassign with torch function
print(torch.sub(temp_tensor, 10.0))

# Matrix multiplication
print(torch.matmul(temp_tensor, temp_tensor.T))


tensor([[11., 12., 13.],
        [14., 15., 16.]])
tensor([[10.2500, 20.5000, 30.7500],
        [41.0000, 51.2500, 61.5000]])
tensor([[-9., -8., -7.],
        [-6., -5., -4.]])
tensor([[14., 32.],
        [32., 77.]])
tensor([[14., 32.],
        [32., 77.]])


In [56]:
#  show the image from the web

image_url = "https://github.com/mrdbourke/pytorch-deep-learning/raw/main/images/00-matrix-multiply-crop.gif"
Image(url= image_url, width=800, height=400)

#### Aggregation in Tensors

In [68]:
#  Create a tensor of size (3,4,2)
temp_tensor = torch.tensor([[[1.0, 2.0], [3.0, 4.0], [5.0, 6.0], [7.0, 8.0]],
                            [[9.0, 10.0], [11.0, 12.0], [
                                13.0, 14.0], [15.0, 16.0]],
                            [[17.0, 18.0], [19.0, 20.0], [21.0, 22.0], [23.0, 24.0]]])
print(temp_tensor.shape)

#  Get the mean of the tensor
print(torch.mean(temp_tensor, dim=0))  # will not work for int dtype
print(torch.mean(temp_tensor, dim=1))  # will not work for int dtype
print(torch.mean(temp_tensor, dim=2))  # will not work for int dtype

print(temp_tensor.mean(dim=0))  # will not work for int dtype
print(temp_tensor.mean(dim=1))  # will not work for int dtype
print(temp_tensor.mean(dim=2))  # will not work for int dtype

#  Get the sum of the tensor
print(torch.sum(temp_tensor, dim=0))
print(torch.sum(temp_tensor, dim=1))
print(torch.sum(temp_tensor, dim=2))

print(temp_tensor.sum(dim=0))
print(temp_tensor.sum(dim=1))
print(temp_tensor.sum(dim=2))

#  Get the max and min of the tensor
print(torch.max(temp_tensor, dim=0))
print(torch.min(temp_tensor, dim=0))

print(temp_tensor.max(dim=0))
print(temp_tensor.min(dim=0))

print(torch.max(temp_tensor, dim=1))
print(torch.min(temp_tensor, dim=1))

print(temp_tensor.max(dim=1))
print(temp_tensor.min(dim=1))

print(torch.max(temp_tensor, dim=2))
print(torch.min(temp_tensor, dim=2))

print(temp_tensor.max(dim=2))
print(temp_tensor.min(dim=2))

torch.Size([3, 4, 2])
tensor([[ 9., 10.],
        [11., 12.],
        [13., 14.],
        [15., 16.]])
tensor([[ 4.,  5.],
        [12., 13.],
        [20., 21.]])
tensor([[ 1.5000,  3.5000,  5.5000,  7.5000],
        [ 9.5000, 11.5000, 13.5000, 15.5000],
        [17.5000, 19.5000, 21.5000, 23.5000]])
tensor([[ 9., 10.],
        [11., 12.],
        [13., 14.],
        [15., 16.]])
tensor([[ 4.,  5.],
        [12., 13.],
        [20., 21.]])
tensor([[ 1.5000,  3.5000,  5.5000,  7.5000],
        [ 9.5000, 11.5000, 13.5000, 15.5000],
        [17.5000, 19.5000, 21.5000, 23.5000]])
tensor([[27., 30.],
        [33., 36.],
        [39., 42.],
        [45., 48.]])
tensor([[16., 20.],
        [48., 52.],
        [80., 84.]])
tensor([[ 3.,  7., 11., 15.],
        [19., 23., 27., 31.],
        [35., 39., 43., 47.]])
tensor([[27., 30.],
        [33., 36.],
        [39., 42.],
        [45., 48.]])
tensor([[16., 20.],
        [48., 52.],
        [80., 84.]])
tensor([[ 3.,  7., 11., 15.],
        [19

In [69]:
#  Create a tensor of size (3,4,2)
temp_tensor = torch.tensor([[[1.0, 2.0], [3.0, 4.0], [5.0, 6.0], [7.0, 8.0]], 
                            [[9.0, 10.0], [11.0, 12.0], [13.0, 14.0], [15.0, 16.0]],
                            [[17.0, 18.0], [19.0, 20.0], [21.0, 22.0], [23.0, 24.0]]])

#  Get the argmax and argmin of the tensor
print(torch.argmax(temp_tensor, dim=0))
print(torch.argmin(temp_tensor, dim=0))

print(temp_tensor.argmax(dim=0))
print(temp_tensor.argmin(dim=0))

print(torch.argmax(temp_tensor, dim=1))
print(torch.argmin(temp_tensor, dim=1))

print(temp_tensor.argmax(dim=1))
print(temp_tensor.argmin(dim=1))

print(torch.argmax(temp_tensor, dim=2))
print(torch.argmin(temp_tensor, dim=2))

print(temp_tensor.argmax(dim=2))
print(temp_tensor.argmin(dim=2))

tensor([[2, 2],
        [2, 2],
        [2, 2],
        [2, 2]])
tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])
tensor([[2, 2],
        [2, 2],
        [2, 2],
        [2, 2]])
tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])
tensor([[3, 3],
        [3, 3],
        [3, 3]])
tensor([[0, 0],
        [0, 0],
        [0, 0]])
tensor([[3, 3],
        [3, 3],
        [3, 3]])
tensor([[0, 0],
        [0, 0],
        [0, 0]])
tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])
tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])
tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])
tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])


#### Change Tensor datatype

In [73]:
# Create a tensor and check its datatype
temp_tensor_fp32 = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
print(temp_tensor.dtype)
print(temp_tensor_fp32.type(dtype= torch.float16))
print(temp_tensor_fp32.type(dtype= torch.int8))

# Create a float16 tensor and check its datatype
temp_tensor_fp16 = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]], dtype=torch.float16)
print(temp_tensor_fp16.dtype)
print(temp_tensor_fp16.type(dtype= torch.float32))
print(temp_tensor_fp16.type(dtype= torch.int8))

# Create a int8 tensor and check its datatype
temp_tensor_int8 = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.int8)
print(temp_tensor_int8.dtype)
print(temp_tensor_int8.type(dtype= torch.float32))
print(temp_tensor_int8.type(dtype= torch.float16))



torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float16)
tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int8)
torch.float16
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int8)
torch.int8
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float16)


#### Reshaping, Stacking, Squeezing and Unsqueezing

In [78]:
#  Create a tensor of size (3,4,2)
temp_tensor = torch.tensor([[[1.0, 2.0], [3.0, 4.0], [5.0, 6.0], [7.0, 8.0]],
                            [[9.0, 10.0], [11.0, 12.0], [13.0, 14.0], [15.0, 16.0]],
                            [[17.0, 18.0], [19.0, 20.0], [21.0, 22.0], [23.0, 24.0]]])

print(temp_tensor.shape)
print(temp_tensor.tolist())

# reshape the tensor
reshaped_tensor = temp_tensor.reshape(2, 6, 2)
print(reshaped_tensor.tolist())
print(reshaped_tensor.shape)

torch.Size([3, 4, 2])
[[[1.0, 2.0], [3.0, 4.0], [5.0, 6.0], [7.0, 8.0]], [[9.0, 10.0], [11.0, 12.0], [13.0, 14.0], [15.0, 16.0]], [[17.0, 18.0], [19.0, 20.0], [21.0, 22.0], [23.0, 24.0]]]
[[[1.0, 2.0], [3.0, 4.0], [5.0, 6.0], [7.0, 8.0], [9.0, 10.0], [11.0, 12.0]], [[13.0, 14.0], [15.0, 16.0], [17.0, 18.0], [19.0, 20.0], [21.0, 22.0], [23.0, 24.0]]]
torch.Size([2, 6, 2])


In [82]:
""" https://tinyurl.com/2jllf5b6
    As the name suggests, torch.view merely creates a view of the original tensor. 
    The new tensor will always share its data with the original tensor. 
    This means that if you change the original tensor, the reshaped tensor will change and vice versa.
"""
temp_tensor = torch.tensor([[[1.0, 2.0], [3.0, 4.0], [5.0, 6.0], [7.0, 8.0]],
                            [[9.0, 10.0], [11.0, 12.0], [13.0, 14.0], [15.0, 16.0]],
                            [[17.0, 18.0], [19.0, 20.0], [21.0, 22.0], [23.0, 24.0]]])

viwed_tensor = temp_tensor.view(2, 6, 2)
print(viwed_tensor.shape)
print(viwed_tensor.tolist())

# Changing the view tensor will change the original tensor
viwed_tensor[:,:, 0] = 0
print(viwed_tensor, temp_tensor)

torch.Size([2, 6, 2])
[[[1.0, 2.0], [3.0, 4.0], [5.0, 6.0], [7.0, 8.0], [9.0, 10.0], [11.0, 12.0]], [[13.0, 14.0], [15.0, 16.0], [17.0, 18.0], [19.0, 20.0], [21.0, 22.0], [23.0, 24.0]]]
tensor([[[ 0.,  2.],
         [ 0.,  4.],
         [ 0.,  6.],
         [ 0.,  8.],
         [ 0., 10.],
         [ 0., 12.]],

        [[ 0., 14.],
         [ 0., 16.],
         [ 0., 18.],
         [ 0., 20.],
         [ 0., 22.],
         [ 0., 24.]]]) tensor([[[ 0.,  2.],
         [ 0.,  4.],
         [ 0.,  6.],
         [ 0.,  8.]],

        [[ 0., 10.],
         [ 0., 12.],
         [ 0., 14.],
         [ 0., 16.]],

        [[ 0., 18.],
         [ 0., 20.],
         [ 0., 22.],
         [ 0., 24.]]])


In [87]:
# Create a tensor of size (2,4)

temp_tensor = torch.tensor([[1.0, 2.0, 3.0, 4.0], [5.0, 6.0, 7.0, 8.0]])

# stack the tensor along the 0th dimension
stacked_tensor = torch.stack([temp_tensor, temp_tensor, temp_tensor], dim=0)
print(stacked_tensor)
print(stacked_tensor.shape)

# stack the tensor along the 1st dimension
stacked_tensor = torch.stack([temp_tensor, temp_tensor, temp_tensor], dim=1)
print(stacked_tensor)
print(stacked_tensor.shape)

# stack the tensor along the 2nd dimension
stacked_tensor = torch.stack([temp_tensor, temp_tensor, temp_tensor], dim=2)
print(stacked_tensor)
print(stacked_tensor.shape)


tensor([[[1., 2., 3., 4.],
         [5., 6., 7., 8.]],

        [[1., 2., 3., 4.],
         [5., 6., 7., 8.]],

        [[1., 2., 3., 4.],
         [5., 6., 7., 8.]]])
torch.Size([3, 2, 4])
tensor([[[1., 2., 3., 4.],
         [1., 2., 3., 4.],
         [1., 2., 3., 4.]],

        [[5., 6., 7., 8.],
         [5., 6., 7., 8.],
         [5., 6., 7., 8.]]])
torch.Size([2, 3, 4])
tensor([[[1., 1., 1.],
         [2., 2., 2.],
         [3., 3., 3.],
         [4., 4., 4.]],

        [[5., 5., 5.],
         [6., 6., 6.],
         [7., 7., 7.],
         [8., 8., 8.]]])
torch.Size([2, 4, 3])


In [98]:
# Create a tensor of size (2,4,1)
temp_tensor = torch.tensor([[1.0, 2.0, 3.0, 4.0], [5.0, 6.0, 7.0, 8.0]])

# Squueze the tensor along the last dimension
squeuezed_tensor = temp_tensor.squeeze(dim=-1)
print(squeuezed_tensor)
print(squeuezed_tensor.shape)

# Unsqueezed the tensor along the last dimension
unsqueezed_tensor = squeuezed_tensor.unsqueeze(dim=-1)
print(unsqueezed_tensor)
print(unsqueezed_tensor.shape)

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])
torch.Size([2, 4])
tensor([[[1.],
         [2.],
         [3.],
         [4.]],

        [[5.],
         [6.],
         [7.],
         [8.]]])
torch.Size([2, 4, 1])


#### Indexing (Selecting Data from Tensors)

In [100]:
# Create a tensor of size (2, 4, 3)
temp_tensor = torch.tensor([[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0], [10.0, 11.0, 12.0]],
                            [[13.0, 14.0, 15.0], [16.0, 17.0, 18.0], [19.0, 20.0, 21.0], [22.0, 23.0, 24.0]]])

# Index bracket by bracket
print(f"First square bracket:\n{temp_tensor[0]}") 
print(f"Second square bracket: {temp_tensor[0][0]}") 
print(f"Third square bracket: {temp_tensor[0][0][0]}")

# Get all values of 0th dimension and the 0 index of 1st dimension
print(f"0th dimension and the 0 index of 1st dimension:\n{temp_tensor[:, 0]}")

# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
print(f"0th & 1st dimensions but only index 1 of 2nd dimension:\n{temp_tensor[:, :, 1]}")

# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
print(f"0th dimension but only the 1 index value of the 1st and 2nd dimension:\n{temp_tensor[:, 1, 1]}")

# Get index 0 of 0th and 1st dimension and all values of 2nd dimension 
print(f"0th and 1st dimension and all values of 2nd dimension:\n{temp_tensor[0, 0, :]}")


First square bracket:
tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
Second square bracket: tensor([1., 2., 3.])
Third square bracket: 1.0
0th dimension and the 0 index of 1st dimension:
tensor([[ 1.,  2.,  3.],
        [13., 14., 15.]])
0th & 1st dimensions but only index 1 of 2nd dimension:
tensor([[ 2.,  5.,  8., 11.],
        [14., 17., 20., 23.]])
0th dimension but only the 1 index value of the 1st and 2nd dimension:
tensor([ 5., 17.])
0th and 1st dimension and all values of 2nd dimension:
tensor([1., 2., 3.])


#### PyTorch Tensors & NumPy

In [103]:
"""
    torch.from_numpy(ndarray) - NumPy array -> PyTorch tensor.
    torch.Tensor.numpy() - PyTorch tensor -> NumPy array.
"""

# Create a numpy array of size (2, 3)
temp_numpy_array = np.array([[1, 2, 3], [4, 5, 6]])
print(temp_numpy_array)

# Convert the numpy array to a tensor
temp_tensor = torch.from_numpy(temp_numpy_array)
print(temp_tensor)

# Convert the tensor to a numpy array
temp_numpy_array = temp_tensor.numpy()
print(temp_numpy_array)

[[1 2 3]
 [4 5 6]]
tensor([[1, 2, 3],
        [4, 5, 6]])
[[1 2 3]
 [4 5 6]]


#### Running Tensors on GPUs

In [104]:
#  check for GPU
print(torch.cuda.is_available())

False


In [105]:
#  Set device type
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [107]:
#  Count the number of GPUs available
print(torch.cuda.device_count())

0


In [111]:
# Create a tensor
temp_tensor = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])

#  Put the tensor on the device
temp_tensor_device = temp_tensor.to(device)
print(temp_tensor, temp_tensor_device)

# Moving tensors back to the CPU
temp_tensor_cpu = temp_tensor_device.to("cpu")
print(temp_tensor_cpu)

tensor([[1., 2., 3.],
        [4., 5., 6.]]) tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
